# Default programs
export EDITOR="nvim"
export VISUAL="nvim"
export FILE="ranger"
export TERMINAL="kitty"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export GOPATH="$HOME/.go"
export PATH="$PATH:$HOME/.local/bin:$GOPATH/bin"
export DENO_INSTALL="/home/eslam/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
. "$HOME/.cargo/env"
